import ClientComponent from '@/lib/ClientComponent'
import StyledComponentsRegistry from '@/lib/registry'
import { Header } from '@/components/Header'
import { GlobalStyle } from '@/styles/GlobalStyle'
import { Rubik, Barlow } from 'next/font/google'
import type { Metadata } from 'next'

const rubik = Rubik({ subsets: ['latin'], weight: ["300", '400', '500', '600', '700'] })
const barlow = Barlow({ subsets: ['latin'], style: 'normal', weight: ["300", '400', '500', '600', '700'] })
export const metadata: Metadata = {
  title: 'Wallace Bezerra',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={`${rubik.className} ${barlow.className}`}>
        <ClientComponent>
          <StyledComponentsRegistry>
            <GlobalStyle />
            <Header />
            {children}
          </StyledComponentsRegistry>
        </ClientComponent>
      </body>
    </html>
  );
}

